name: dev - lint
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: 'pip'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - run: pip install -r requirements.txt
      - run: pylama | reviewdog -efm="%f:%l:%c %m" -diff="git diff FETCH_HEAD"