name: dev - lint
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      uses: actions/setup-python@v2
        - cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pylama