name: CI - Redeploy

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Send redeploy hook"
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
